name: pippo
favicon: null
layout_spectrum: 0.8246710665989667
typography_spectrum: 0.820602138293907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.41333209862932563
  lightness: 0.5670750802382827
  saturation: 0.24838612112216651
  rhythmicContrast: 0.4937149756588042
purpose: []
